### PR TITLE
Add elFinder dark mode

### PR DESCRIPTION
**Pull request by jorgetwgroup**
This PR will fix dark mode on elFinder https://github.com/Laravel-Backpack/theme-tabler/issues/103

### CODE REVIEW

**Comment by jorgetwgroup** [comment]
Hi.

Here are the elFinder problems.

Screenshot 2023-07-24 at 08 26 54

As we speak i try to change background with css, was not possible, because is HTML inside popup. i Find information in this blog https://fvsch.com/transparent-iframes and i try:

`<meta name="color-scheme" content="dark" />`

thats work for dark:

Screenshot 2023-07-24 at 08 24 38

But create a problem for light:

Screenshot 2023-07-24 at 08 25 35

When i try to delete the meta tag, still have the problem.

Thanks for help.

**Comment by jorgetwgroup** [comment]
Hello @pxpm can you test about tinyMCE, is needed to pull this branch and as your instructions "Also if you already have elfinder installed you should delete the elfinder views from your resources/views/vendor/elfinder folder and publish them again with php artisan backpack:filemanager:install" Thanks

**Comment by tabacitu** [comment]
Any chance we can bundle the delete&copy of the blade files into one command, something like `php artisan backpack:filemanager:install --force`?

**Comment by pxpm** [comment]
Hey @jorgetwgroup 

This is close to be done but not quite yet. 

I notice the following:
- If I start my page light. 
- Then I switch to dark (without reloading the page)
- When I open the popup it opens with "light" theme, and then flicks for the "dark". 

I think it happens because you used your old solution and didn't implemented the same solution I did in the `standalonepopup` and `elfinder` files that fix this. 

Let me know.

Cheers

**Comment by jorgetwgroup** [comment]
Hello @pxpm didnt fail on my side, but in any case i do as you say.

Thanks.

**Pull request merged**
