### PR TITLE
fix a lack of steps

### PR DESCRIPTION
**Pull request by mansourcodes**
I have faced two issues because of this lack of steps,
I hope it's added to the README.md

### CODE REVIEW

**Comment by promatik** [comment]
Hi @mansourcodes, that's pretty odd, have you run `php artisan backpack:filemanager:install`?

Because that command will run everything, take a look;
https://github.com/Laravel-Backpack/FileManager/blob/master/src/Console/Commands/Install.php

**Comment by mansourcodes** [comment]
yes, I did run `php artisan backpack:filemanager:install`

maybe because I copied elfinder view and config before installing backpack\filemanager ?

**Comment by promatik** [comment]
@mansourcodes maybe, I tried here, and by following the installation steps everything works as expected, if you can, please try it on a fresh Laravel install:
- `composer require backpack/crud:"4.1.*"`
- `php artisan backpack:install`
- `composer require backpack/filemanager`
- `php artisan backpack:filemanager:install`

**Comment by mansourcodes** [comment]
working Great.

it was **my fault** when I installed it after reading the following steps.
```
Backpack admin interface for files and folder, using barryvdh/laravel-elfinder. This package literally just:

creates a public/uploads folder;
installs barryvdh/laravel-elfinder;
publishes an elFinder config and view, for elFinder to play nice with Backpack;
adds a menu item to the sidebar;
```

**Comment by promatik** [comment]
Great @mansourcodes 🙌
For now I'll close this PR.

**Pull request closed without merging**
