### PR TITLE
Translate File Manager heading and breadcrumb in views/elfinder.blade.php

### PR DESCRIPTION
**Pull request by jnoordsij**
Use translated name of File Manager in view.

### CODE REVIEW

**Comment by jnoordsij** [comment]
@tabacitu any chance of getting this in? :smile:

**Review by promatik — APPROVED** [review]

**Comment by promatik** [comment]
Hi @jnoordsij!
Thank you for this, it's a tiny detail that slipped through us 😅
I'm moving this to _Ready to Merge_, so Tabacitu will take a look very soon!

**Comment by jnoordsij** [comment]
No problem, already figured this repo is probably somewhat hidden when going about, hence the headsup. Thanks for looking into this!

**Comment by tabacitu** [comment]
Ouch - sorry for the delay @jnoordsij . This must have slipped through the cracks. Merged, tagging right now. Thanks for the help 🙏

**Pull request merged**
